import { db } from '../../config/firebase';
import { doc, setDoc } from 'firebase/firestore';

export const addCollegeData = async () => {
  const CollegeData = {
    UK: [
      {
        name: 'Anglia Ruskin University',
        img: 'https://www.britishcouncil.or.th/sites/default/files/anglia_ruskin_university.jpg ',
        youtube: ' http://www.youtube.com/watch?v=5zp3sYc3qfg',
        location: 'Cambridge, England',
        website: 'https://aru.ac.uk',
      },
      {
        name: 'Bangor University',
        img: ' https://www.thecompleteuniversityguide.co.uk/commimg-cug/myhotcourses/institution/profile/image/myhc_327725_1106px.jpg',
        youtube: 'http://www.youtube.com/watch?v=5zp3sYc3qfg ',
        location: 'Bangor, Wales',
        website: 'https://www.bangor.ac.uk',
      },
      {
        name: 'Birkbeck University of London',
        img: ' https://edysor.in/images/university/banner/1676028152.webp',
        youtube: 'http://www.youtube.com/watch?v=5zp3sYc3qfg ',
        location: 'London, England',
        website: 'https://www.bbk.ac.uk',
      },
      {
        name: 'Birmingham City University',
        img: 'https://images.shiksha.com/mediadata/images/1537953425phpglydC8.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=5zp3sYc3qfg',
        location: 'Birmingham, England',
        website: 'https://www.bcu.ac.uk',
      },
      {
        name: 'Bournemouth University',
        img: ' https://www.bournemouth.ac.uk/sites/default/files/styles/b_16_9_desktop/public/assets/images/student-centre-new-hero.jpg?itok=C1HMZXwe',
        youtube: ' http://www.youtube.com/watch?v=5zp3sYc3qfg',
        location: 'Bournemouth, England',
        website: 'https://www.bournemouth.ac.uk',
      },
      {
        name: 'Brunel University',
        img: ' https://images.shiksha.com/mediadata/images/1535104347phpAH9RQx.jpeg',
        youtube: ' http://www.youtube.com/watch?v=5zp3sYc3qfg',
        location: 'London, England',
        website: 'https://www.brunel.ac.uk',
      },
      {
        name: 'Cardiff University',
        img: ' https://images.shiksha.com/mediadata/images/1534412382phpYPav1d.jpeg',
        youtube: ' http://www.youtube.com/watch?v=5zp3sYc3qfg',
        location: 'Cardiff, Wales',
        website: 'https://www.cardiff.ac.uk',
      },
      {
        name: 'City University London',
        img: 'https://www.london.ac.uk/sites/default/files/City%20University%20of%20London.jpg ',
        youtube: ' http://www.youtube.com/watch?v=5zp3sYc3qfg',
        location: 'London, England',
        website: 'https://www.city.ac.uk',
      },
      {
        name: 'Coventry University',
        img: 'https://images.shiksha.com/mediadata/images/1535015055phpMMRSDL_g.jpg ',
        youtube: 'http://www.youtube.com/watch?v=pX9SQXGG0ho ',
        location: 'Coventry, England',
        website: 'https://www.coventry.ac.uk',
      },
      {
        name: 'De Montfort University',
        img: ' https://accommodationforstudents.com/cdn-cgi/image/f=auto,q=85,w=960/https://images.accommodationforstudents.com/website/university-guides/gb/de-montfort-university/uni.jpg',
        youtube: ' http://www.youtube.com/watch?v=pX9SQXGG0ho',
        location: 'Leicester, England',
        website: 'https://www.dmu.ac.uk',
      },
      {
        name: 'Durham University',
        img: 'https://images.shiksha.com/mediadata/images/1500456340phpN4RhCN.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=pX9SQXGG0ho ',
        location: 'Durham, England',
        website: 'https://www.durham.ac.uk',
      },
      {
        name: 'Edinburgh Napier University',
        img: ' https://images.shiksha.com/mediadata/images/1536658853phpxe5HqI.jpeg',
        youtube: ' http://www.youtube.com/watch?v=pX9SQXGG0ho',
        location: 'Edinburgh, Scotland',
        website: 'https://www.napier.ac.uk',
      },
      {
        name: 'Glasgow Caledonian University',
        img: 'https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/CH/myhc_299516.jpg ',
        youtube: 'http://www.youtube.com/watch?v=wWolFUTzvwY ',
        location: 'Glasgow, Scotland',
        website: 'https://www.gcu.ac.uk',
      },
      {
        name: 'Goldsmiths University of London',
        img: 'https://www.gold.ac.uk/media/images-by-section/about-us/heroes/about-50-50-hero.jpg ',
        youtube: ' http://www.youtube.com/watch?v=wWolFUTzvwY',
        location: 'London, England',
        website: 'https://www.gold.ac.uk',
      },
      {
        name: 'Heriot-Watt University',
        img: ' https://www.hw.ac.uk/img/students-loch-bridge-900x450_rdax_640x320_75p.jpg',
        youtube: 'http://www.youtube.com/watch?v=wWolFUTzvwY',
        location: 'Edinburgh, Scotland',
        website: 'https://www.hw.ac.uk',
      },
      {
        name: 'Kingston University',
        img: ' https://cdn.kingston.ac.uk/includes/img/cms/site-images/resized/cc361241855-kingston-university-d65287a3462-.jpg',
        youtube: ' http://www.youtube.com/watch?v=2w3OX9fv5Vk',
        location: 'Kingston upon Thames, England',
        website: 'https://www.kingston.ac.uk',
      },
      {
        name: 'Leeds Beckett University',
        img: 'https://images.shiksha.com/mediadata/images/1538131314phpYhMPZu.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=2w3OX9fv5Vk ',
        location: 'Leeds, England',
        website: 'https://www.leedsbeckett.ac.uk',
      },
      {
        name: 'University of Lincoln',
        img: 'https://images.shiksha.com/mediadata/images/1535086083phpnFGvGd.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=4aset4B1CE8',
        location: 'Lincoln, England',
        website: 'https://www.lincoln.ac.uk',
      },
      {
        name: 'London Metropolitan University',
        img: ' https://libeskind.com/wp-content/uploads/elevation-from-northeast-c-bitterbredt-2280x1485.jpg',
        youtube: ' http://www.youtube.com/watch?v=54Mz2kLnBdk',
        location: 'London, England',
        website: 'https://www.londonmet.ac.uk',
      },
      {
        name: 'London South Bank University',
        img: ' https://images.shiksha.com/mediadata/images/1539083243phpIBxqhS.jpeg',
        youtube: ' http://www.youtube.com/watch?v=z0im_ysNHok',
        location: 'London, England',
        website: 'https://www.lsbu.ac.uk',
      },
      {
        name: 'Loughborough University',
        img: ' https://www.chevening.org/wp-content/uploads/2023/08/Hazlerigg-scaled.jpg',
        youtube: 'http://www.youtube.com/watch?v=8RHZ1K-ev2w ',
        location: 'Loughborough, England',
        website: 'https://www.lboro.ac.uk',
      },
      {
        name: 'Middlesex University',
        img: ' https://images.shiksha.com/mediadata/images/1505799540phprXYrTp.jpeg',
        youtube: ' http://www.youtube.com/watch?v=tIP3tW9MACk',
        location: 'London, England',
        website: 'https://www.mdx.ac.uk',
      },
      {
        name: 'Newcastle University',
        img: ' https://images.shiksha.com/mediadata/images/1534939277phpGjaL0k_g.jpg',
        youtube: 'http://www.youtube.com/watch?v=vJUfHcqB7l8 ',
        location: 'Newcastle upon Tyne, England',
        website: 'https://www.ncl.ac.uk',
      },
      {
        name: 'Northumbria University',
        img: 'https://images.shiksha.com/mediadata/images/1535022251php6npTks.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=VsyjeS1tkvc',
        location: 'Newcastle upon Tyne, England',
        website: 'https://www.northumbria.ac.uk',
      },
      {
        name: 'Nottingham Trent University',
        img: 'https://images.shiksha.com/mediadata/images/1533899411phpMRcyBS.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=0c-zNdMACls ',
        location: 'Nottingham, England',
        website: 'https://www.ntu.ac.uk',
      },
      {
        name: 'Oxford Brookes University',
        img: ' https://theoxfordmagazine.com/wp-content/uploads/oxford-brookes-university-sir-kenneth-wheare-hall-headington-01-1600x900-1-jpg.webp',
        youtube: 'http://www.youtube.com/watch?v=pAK6c4zt4JI ',
        location: 'Oxford, England',
        website: 'https://www.brookes.ac.uk',
      },
      {
        name: 'Queen Mary University of London',
        img: 'https://images.shiksha.com/mediadata/images/1549017501phpnVok42.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=ocVdSam7GP8',
        location: 'London, England',
        website: 'https://www.qmul.ac.uk',
      },
      {
        name: "Queen's University Belfast",
        img: 'https://images.shiksha.com/mediadata/images/1508929173phpZVGfRe.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=ocVdSam7GP8',
        location: 'Belfast, Northern Ireland',
        website: 'https://www.qub.ac.uk',
      },
      {
        name: 'Robert Gordon University',
        img: 'https://media.studentcrowd.net/w852-h568-q90-cfill/1442241735_uploaded.jpg ',
        youtube: ' http://www.youtube.com/watch?v=edWPU2OLtp8',
        location: 'Aberdeen, Scotland',
        website: 'https://www.rgu.ac.uk',
      },
      {
        name: 'Royal Holloway University of London',
        img: ' https://b-imm.com/wp-content/uploads/2024/01/Img-RoyalHolloway-Feature.jpg',
        youtube: ' http://www.youtube.com/watch?v=xGPC0cKDgZo',
        location: 'Egham, England',
        website: 'https://www.royalholloway.ac.uk',
      },
      {
        name: 'SOAS University of London',
        img: ' https://soasalumni.org/wp-content/uploads/2021/11/1.jpg',
        youtube: ' http://www.youtube.com/watch?v=oqzzFTsONjg',
        location: 'London, England',
        website: 'https://www.soas.ac.uk',
      },
      {
        name: 'Sheffield Hallam University',
        img: ' https://images.shiksha.com/mediadata/images/1401085051phpqdDPuQ.jpeg',
        youtube: ' http://www.youtube.com/watch?v=AFWXyLrIha0',
        location: 'Sheffield, England',
        website: 'https://www.shu.ac.uk',
      },
      {
        name: 'Solent University',
        img: ' https://images.shiksha.com/mediadata/images/1399526781phpnWrH2c.jpeg',
        youtube: ' http://www.youtube.com/watch?v=H8QUSTAc2T8',
        location: 'Southampton, England',
        website: 'https://www.solent.ac.uk',
      },
      {
        name: 'Swansea University',
        img: 'https://applyzones.com/uploads/schools/az-swansea-university.jpg ',
        youtube: ' http://www.youtube.com/watch?v=dB_fXRuqh_A',
        location: 'Swansea, Wales',
        website: 'https://www.swansea.ac.uk',
      },
      {
        name: 'Teesside University',
        img: ' https://images.shiksha.com/mediadata/images/1505278845phpBPeYvg.jpeg',
        youtube: ' http://www.youtube.com/watch?v=fX-OGoDPRxU',
        location: 'Middlesbrough, England',
        website: 'https://www.tees.ac.uk',
      },
      {
        name: 'The University of Edinburgh',
        img: 'https://www.ed.ac.uk/sites/default/files/thumbnails/image/cam_about-us-1_old_college_0.jpg ',
        youtube: ' http://www.youtube.com/watch?v=mVOmZkvLbQw',
        location: 'Edinburgh, Scotland',
        website: 'https://www.ed.ac.uk',
      },
      {
        name: 'The University of Nottingham',
        img: ' https://images.shiksha.com/mediadata/images/1534249812phpzcnHAe.jpeg',
        youtube: ' http://www.youtube.com/watch?v=iBUQKIuaoTE',
        location: 'Nottingham, England',
        website: 'https://www.nottingham.ac.uk',
      },
      {
        name: 'The University of Sheffield',
        img: ' https://images.shiksha.com/mediadata/images/1541413835phptim5jy.jpeg',
        youtube: ' http://www.youtube.com/watch?v=BoIZJjrKW-4',
        location: 'Sheffield, England',
        website: 'https://www.sheffield.ac.uk',
      },
      {
        name: 'University for the Creative Arts',
        img: 'https://images.shiksha.com/mediadata/images/1495605792phpNksALN.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=aTpdAIWWbDI',
        location: 'Farnham, England',
        website: 'https://www.uca.ac.uk',
      },
      {
        name: 'University of Bedfordshire',
        img: 'https://keystoneacademic-res.cloudinary.com/image/upload/element/22/221027_220418_cover_photo-Postgraduate-Centre-2022-15.jpg ',
        youtube: ' http://www.youtube.com/watch?v=Anq9fVm8HpI',
        location: 'Luton, England',
        website: 'https://www.beds.ac.uk',
      },
      {
        name: 'University of Bolton',
        img: ' https://images.shiksha.com/mediadata/images/1540798024php0FJ187.jpeg',
        youtube: ' http://www.youtube.com/watch?v=WIh15eEd5N8',
        location: 'Bolton, England',
        website: 'https://www.bolton.ac.uk',
      },
      {
        name: 'University of Brighton',
        img: ' https://c.files.bbci.co.uk/3d45/live/06d10690-143c-11ef-b0d8-137e1a51c92d.jpg',
        youtube: ' http://www.youtube.com/watch?v=3JxhzOL2yR8',
        location: 'Brighton, England',
        website: 'https://www.brighton.ac.uk',
      },
      {
        name: 'University of Central Lancashire',
        img: ' https://images.shiksha.com/mediadata/images/1493896153phpvvrfdy.jpeg',
        youtube: 'http://www.youtube.com/watch?v=rYW88zlCP8c ',
        location: 'Preston, England',
        website: 'https://www.uclan.ac.uk',
      },
      {
        name: 'University of Dundee',
        img: 'https://images.shiksha.com/mediadata/images/1536661489phpveDIlW.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=SqvXL4cli6A',
        location: 'Dundee, Scotland',
        website: 'https://www.dundee.ac.uk',
      },
      {
        name: 'University of East Anglia',
        img: ' https://images.shiksha.com/mediadata/images/1538993958phpSkMphT.png',
        youtube: ' http://www.youtube.com/watch?v=FTQ0wAVXfXY',
        location: 'Norwich, England',
        website: 'https://www.uea.ac.uk',
      },
      {
        name: 'University of East London',
        img: ' https://images.shiksha.com/mediadata/images/1537954598php7mKNkH.jpeg',
        youtube: 'http://www.youtube.com/watch?v=pGy4Z44DSfk ',
        location: 'London, England',
        website: 'https://www.uel.ac.uk',
      },
      {
        name: 'University of Essex',
        img: ' https://images.shiksha.com/mediadata/images/1537166112php0PZWLJ_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=oPUKXSEMZQU',
        location: 'Colchester, England',
        website: 'https://www.essex.ac.uk',
      },
      {
        name: 'University of Exeter',
        img: ' https://edysor.in/images/university/banner/University-of-Exeter.webp',
        youtube: ' http://www.youtube.com/watch?v=BUN0sSa2e9c',
        location: 'Exeter, England',
        website: 'https://www.exeter.ac.uk',
      },
      {
        name: 'University of Glasgow',
        img: ' https://cfmnsugzia.cloudimg.io/www.gla.ac.uk/media/Media_714393_smxx.jpg?width=1400&force_format=webp',
        youtube: 'http://www.youtube.com/watch?v=pEPLWygiRJk ',
        location: 'Glasgow, Scotland',
        website: 'https://www.gla.ac.uk',
      },
      {
        name: 'University of Greenwich',
        img: 'https://mediaim.expedia.com/destination/2/c8f1e98007c3c3791ed0d0a61f2db1bf.jpg ',
        youtube: 'http://www.youtube.com/watch?v=ZsBJPaHnESY ',
        location: 'London, England',
        website: 'https://www.gre.ac.uk',
      },
      {
        name: 'University of Hertfordshire',
        img: ' https://images.shiksha.com/mediadata/images/1533895092phpoIejGB.jpeg',
        youtube: 'http://www.youtube.com/watch?v=Ol80Y10Me_8 ',
        location: 'Hatfield, England',
        website: 'https://www.herts.ac.uk',
      },
      {
        name: 'University of Huddersfield',
        img: 'https://images.shiksha.com/mediadata/images/1476779192php1UZAwP.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=vk15Kr0q-3s',
        location: 'Huddersfield, England',
        website: 'https://www.hud.ac.uk',
      },
      {
        name: 'University of Kent',
        img: ' https://images.shiksha.com/mediadata/images/1534847210php7iey9f.jpeg',
        youtube: 'http://www.youtube.com/watch?v=BxsFDQLVV7U ',
        location: 'Canterbury, England',
        website: 'https://www.kent.ac.uk',
      },
      {
        name: 'University of Leicester',
        img: 'https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/CH/myhc_303554.jpg ',
        youtube: ' http://www.youtube.com/watch?v=mQCoHdorhaI',
        location: 'Leicester, England',
        website: 'https://le.ac.uk',
      },
      {
        name: 'University of Liverpool',
        img: ' https://images.shiksha.com/mediadata/images/1398677512phpKUT2VW.jpeg',
        youtube: 'http://www.youtube.com/watch?v=FxfzRUk1mKc ',
        location: 'Liverpool, England',
        website: 'https://www.liverpool.ac.uk',
      },
      {
        name: 'University of Northampton',
        img: 'https://images.shiksha.com/mediadata/images/1544164615phpEXodJC.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=fI51QYHliA4',
        location: 'Northampton, England',
        website: 'https://www.northampton.ac.uk',
      },
      {
        name: 'University of Plymouth',
        img: ' https://images.shiksha.com/mediadata/images/1538110096phpOcpuQZ.jpeg',
        youtube: 'http://www.youtube.com/watch?v=iRIBbjmj670 ',
        location: 'Plymouth, England',
        website: 'https://www.plymouth.ac.uk',
      },
      {
        name: 'University of Portsmouth',
        img: ' https://images.shiksha.com/mediadata/images/1683613825php9DB7Mw.jpeg',
        youtube: 'http://www.youtube.com/watch?v=gp_Tm2MvzFU ',
        location: 'Portsmouth, England',
        website: 'https://www.port.ac.uk',
      },
      {
        name: 'University of Reading',
        img: ' https://images.shiksha.com/mediadata/images/1537948985php5WxNlJ.jpeg',
        youtube: ' http://www.youtube.com/watch?v=aMqk7xtLds0',
        location: 'Reading, England',
        website: 'https://www.reading.ac.uk',
      },
      {
        name: 'University of Roehampton',
        img: ' https://www.seatssoftware.com/wp-content/uploads/2024/06/University-Roehampton.jpg',
        youtube: 'http://www.youtube.com/watch?v=Rfi_P7Q6lus ',
        location: 'London, England',
        website: 'https://www.roehampton.ac.uk',
      },
      {
        name: 'University of Salford',
        img: ' https://edysor.in/images/university/banner/University-of-Salford.webp',
        youtube: ' http://www.youtube.com/watch?v=bIBnL4LijkY',
        location: 'Salford, England',
        website: 'https://www.salford.ac.uk',
      },
      {
        name: 'University of Southampton',
        img: 'https://images.shiksha.com/mediadata/images/1534154964phpGaQeW5.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=0nSGL8tZsUQ ',
        location: 'Southampton, England',
        website: 'https://www.southampton.ac.uk',
      },
      {
        name: 'University of Stirling',
        img: ' https://edysor.in/images/university/banner/University-of-Stirling.webp',
        youtube: ' http://www.youtube.com/watch?v=a_x_ISVibPA',
        location: 'Stirling, Scotland',
        website: 'https://www.stir.ac.uk',
      },
      {
        name: 'University of Strathclyde',
        img: ' ',
        youtube: 'http://www.youtube.com/watch?v=58pmA-fqYQ0 ',
        location: 'Glasgow, Scotland',
        website: 'https://www.strath.ac.uk',
      },
      {
        name: 'University of Surrey',
        img: ' https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/New_Strathclyde_Business_School_.jpg/288px-New_Strathclyde_Business_School_.jpg',
        youtube: 'http://www.youtube.com/watch?v=SwCf8B07_s8 ',
        location: 'Guildford, England',
        website: 'https://www.surrey.ac.uk',
      },
      {
        name: 'University of Sussex',
        img: 'https://www.sussex.ac.uk/wcm/assets/media/original/40658.jpg ',
        youtube: 'http://www.youtube.com/watch?v=VAoIkGM1s_c ',
        location: 'Brighton, England',
        website: 'https://www.sussex.ac.uk',
      },
      {
        name: 'Ulster University',
        img: ' https://www.ulster.ac.uk/__data/assets/image/0004/1288795/20451.jpg',
        youtube: 'http://www.youtube.com/watch?v=mALYlZ54wjM ',
        location: 'Northern Ireland',
        website: 'https://www.ulster.ac.uk',
      },
      {
        name: 'University of the West of England',
        img: ' https://images.shiksha.com/mediadata/images/1623052710phpHHrj0i.jpeg',
        youtube: ' http://www.youtube.com/watch?v=Gf1vJwkgZQU',
        location: 'Bristol, England',
        website: 'https://www.uwe.ac.uk',
      },
      {
        name: 'University of Warwick',
        img: ' https://images.shiksha.com/mediadata/images/1533642997phpf8SqM8.jpeg',
        youtube: ' http://www.youtube.com/watch?v=0QPwypDDsME',
        location: 'Coventry, England',
        website: 'https://warwick.ac.uk',
      },
      {
        name: 'University of Westminster',
        img: ' https://images.shiksha.com/mediadata/images/1399274501phpH9C9L4.jpeg',
        youtube: 'http://www.youtube.com/watch?v=0ncjkJv5KbU ',
        location: 'London, England',
        website: 'https://www.westminster.ac.uk',
      },
      {
        name: 'University of Wolverhampton',
        img: ' https://www.opendays.com/images/profiles/257_ov1.png',
        youtube: ' http://www.youtube.com/watch?v=NgzcOUz2yp8',
        location: 'Wolverhampton, England',
        website: 'https://www.wlv.ac.uk',
      },
      {
        name: 'University of York',
        img: 'https://images.shiksha.com/mediadata/images/1502275045phpRDE4IE.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=IIuv2Y5DZoo',
        location: 'York, England',
        website: 'https://www.york.ac.uk',
      },
    ],
    USA: [
      {
        name: 'University of Alabama',
        img: ' https://images.shiksha.com/mediadata/images/1534841399php3BlKjv_205x160.jpg',
        youtube: ' https://www.youtube.com/watch?v=90PRZhLeerE',
        location: 'Alabama, USA',
        website: 'https://www.ua.edu',
      },
      {
        name: 'University of Bridgeport',
        img: ' https://images.shiksha.com/mediadata/images/1534761331phpDOUtAZ_205x160.jpg',
        youtube: 'https://www.youtube.com/watch?v=x-pMiNyzMq8 ',
        location: 'Bridgeport, Connecticut, USA',
        website: 'https://www.bridgeport.edu',
      },
      {
        name: 'Arkansas State University',
        img: ' https://images.shiksha.com/mediadata/images/1536749325phphLAzZA_g.jpg',
        youtube: 'http://www.youtube.com/watch?v=0q9fFiafVPs ',
        location: 'Jonesboro, Arkansas, USA',
        website: 'https://www.astate.edu',
      },
      {
        name: 'California State University San Marcos',
        img: ' https://www.calstate.edu/attend/campuses/SiteAssets/campus-facts/campus-fact-data/campus-images/SAN%20MARCOS/san%20marcos-1.jpg',
        youtube: 'http://www.youtube.com/watch?v=hj99AFQbJ3I ',
        location: 'San Marcos, California, USA',
        website: 'https://www.csusm.edu',
      },
      {
        name: 'California State University San Bernardino',
        img: 'https://images.shiksha.com/mediadata/images/1423735771phppeJstq_205x160.jpg ',
        youtube: 'http://www.youtube.com/watch?v=r1A29Rieq1c ',
        location: 'San Bernardino, California, USA',
        website: 'https://www.csusb.edu',
      },
      {
        name: 'California State University Stanislaus',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNnElIYzp8wCSsQnIBJuK4UZ_mxekOCbwMWQ&s',
        youtube: ' http://www.youtube.com/watch?v=DES5WNK4guo',
        location: 'Turlock, California, USA',
        website: 'https://www.csustan.edu',
      },
      {
        name: 'Clarkson University',
        img: ' https://www.clarkson.edu/sites/default/files/2023-07/student-center-hero-1600x900_0.jpg',
        youtube: ' http://www.youtube.com/watch?v=DES5WNK4guo',
        location: 'Potsdam, New York, USA',
        website: 'https://www.clarkson.edu',
      },
      {
        name: 'Dallas Baptist University',
        img: ' https://dbupatriots.com/images/2016/8/19/DSC_4974.jpg',
        youtube: ' http://www.youtube.com/watch?v=DES5WNK4guo',
        location: 'Dallas, Texas, USA',
        website: 'https://www.dbu.edu',
      },
      {
        name: 'Florida International University',
        img: ' https://www.fiu.edu/_assets/images/cover.jpg?id=2a56da8b0a73710b5d5807d6a3a4190d',
        youtube: ' http://www.youtube.com/watch?v=DES5WNK4guo',
        location: 'Miami, Florida, USA',
        website: 'https://www.fiu.edu',
      },
      {
        name: 'Florida Institute of Technology',
        img: 'https://uniabroad.io/storage/featuredImage/1670586109-banner-Florida%20Institute%20of%20Technology.webp ',
        youtube: ' http://www.youtube.com/watch?v=DES5WNK4guo',
        location: 'Melbourne, Florida, USA',
        website: 'https://www.fit.edu',
      },
      {
        name: 'Grand Valley State University',
        img: ' https://s3-rd-prod.crainsdetroit.com/styles/1200x630/s3/2000%5B1654174638%5D.jpg',
        youtube: 'http://www.youtube.com/watch?v=Z_duFeN49PY ',
        location: 'Allendale, Michigan, USA',
        website: 'https://www.gvsu.edu',
      },
      {
        name: 'Globe University',
        img: ' https://leapassets.s3.ap-south-1.amazonaws.com/Globe_University_i_7ce38e40df.jpg',
        youtube: 'http://www.youtube.com/watch?v=75A9Sj-p4HY ',
        location: 'Various Locations, USA',
        website: 'https://www.globeuniversity.edu',
      },
      {
        name: 'Hamline University',
        img: ' https://www.hamline.edu/sites/default/files/styles/scale_width_1920/public/2023-09/STUD33610556.jpg?h=56d0ca2e&itok=8WV_s7xK',
        youtube: ' http://www.youtube.com/watch?v=e0_dcJ4g3eY',
        location: 'Saint Paul, Minnesota, USA',
        website: 'https://www.hamline.edu',
      },
      {
        name: 'Indiana State University',
        img: 'https://apply-indstate-edu.cdn.technolutions.net/www/images/20221007_Fountain_dede_plaza-7001-X2.jpg ',
        youtube: ' http://www.youtube.com/watch?v=e0_dcJ4g3eY ',
        location: 'Terre Haute, Indiana, USA',
        website: 'https://www.indstate.edu',
      },
      {
        name: 'International Technological University',
        img: ' https://images.shiksha.com/mediadata/images/1613382895phpVtPoRF.jpeg',
        youtube: ' http://www.youtube.com/watch?v=e0_dcJ4g3eY',
        location: 'Santa Clara, California, USA',
        website: 'https://www.itu.edu',
      },
      {
        name: 'James Madison University',
        img: ' https://uniabroad.io/storage/featuredImage/1672641626-banner-James%20Madison%20University.webp',
        youtube: ' http://www.youtube.com/watch?v=e0_dcJ4g3eY',
        location: 'Harrisonburg, Virginia, USA',
        website: 'https://www.jmu.edu',
      },
      {
        name: 'Jacksonville University',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/JU2014.JPG/300px-JU2014.JPG ',
        youtube: 'http://www.youtube.com/watch?v=_h8T7lDWj9s ',
        location: 'Jacksonville, Florida, USA',
        website: 'https://www.ju.edu',
      },
      {
        name: 'Kansas State University',
        img: ' https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_800,q_75,w_1200/v1/clients/manhattanks/Anderson_Hall_1f1567eb-cdb7-4c16-bffd-20ad569c7adc.jpg',
        youtube: 'http://www.youtube.com/watch?v=Zs-q1Rl3FmQ ',
        location: 'Manhattan, Kansas, USA',
        website: 'https://www.k-state.edu',
      },
      {
        name: 'Kent State University',
        img: 'https://www-s3-live.kent.edu/s3fs-root/s3fs-public/page/B0B_0985.jpg?VersionId=_KlT8.k6vjcnZhrsUEl_UJEHP2ruHeSQ ',
        youtube: ' http://www.youtube.com/watch?v=oSPhZ-Hie3A',
        location: 'Kent, Ohio, USA',
        website: 'https://www.kent.edu',
      },
      {
        name: 'Liberty University',
        img: ' https://cicv.org/wp-content/uploads/2023/08/LibertyThumb.jpg',
        youtube: ' http://www.youtube.com/watch?v=nOrl6gE88FI',
        location: 'Lynchburg, Virginia, USA',
        website: 'https://www.liberty.edu',
      },
      {
        name: 'La Salle University',
        img: ' https://www.lasalle.edu/wp-content/uploads/2023/08/Campus-008.png',
        youtube: 'http://www.youtube.com/watch?v=9Gu8SNkMz1k ',
        location: 'Philadelphia, Pennsylvania, USA',
        website: 'https://www.lasalle.edu',
      },
      {
        name: 'Midwestern State University',
        img: ' https://msutexas.edu/_assets/img/social-share.jpg',
        youtube: ' http://www.youtube.com/watch?v=M4jwoqiXPFk',
        location: 'Wichita Falls, Texas, USA',
        website: 'https://www.msutexas.edu',
      },
      {
        name: 'Manhattan Institute of Management',
        img: ' https://goldstareducation.com/wp-content/uploads/2024/02/manhattan-institute-of-management.jpg',
        youtube: 'http://www.youtube.com/watch?v=M4jwoqiXPFk ',
        location: 'New York, USA',
        website: 'https://www.mimusa.edu',
      },
      {
        name: 'Missouri University of Science and Technology',
        img: 'https://marvel-b1-cdn.bc0a.com/f00000000290162/images.ctfassets.net/2htm8llflwdx/35jl9doBOzzQ3K8zHVxPC3/a28700568ef85828b83a3b26847c2134/20210908_campus_1.jpg?fit=thumb&w=1280&h=720 ',
        youtube: 'http://www.youtube.com/watch?v=lWCY4vpql9s ',
        location: 'Rolla, Missouri, USA',
        website: 'https://www.mst.edu',
      },
      {
        name: 'Mountain State University',
        img: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmrF__zFzvZYy6D81JRuUkO4-9si8-6Lm-dA&s',
        youtube: ' http://www.youtube.com/watch?v=lWCY4vpql9s',
        location: 'Beckley, West Virginia, USA',
        website: 'https://www.mountainstate.edu',
      },
      {
        name: 'University of Massachusetts Boston',
        img: ' https://www.usnews.com/dims4/USNEWS/b6ff16d/17177859217/resize/800x540%3E/quality/85/?url=https%3A%2F%2Fwww.usnews.com%2Fcmsmedia%2F05%2Fd8dafebbabfd2b8e4145176be41aec%2Fcollege-photo_29208.jpg',
        youtube: ' http://www.youtube.com/watch?v=dv6CIqf2QpU',
        location: 'Boston, Massachusetts, USA',
        website: 'https://www.umb.edu',
      },
      {
        name: 'University of Massachusetts Lowell',
        img: ' https://images.shiksha.com/mediadata/images/1552291072phpEsCHeE.jpeg',
        youtube: ' http://www.youtube.com/watch?v=dv6CIqf2QpU',
        location: 'Lowell, Massachusetts, USA',
        website: 'https://www.uml.edu',
      },
      {
        name: 'University of Massachusetts Dartmouth',
        img: ' https://images.shiksha.com/mediadata/images/1622013701phpXtdsaI.jpeg',
        youtube: 'http://www.youtube.com/watch?v=-FdStCQ4llU ',
        location: 'Dartmouth, Massachusetts, USA',
        website: 'https://www.umassd.edu',
      },
      {
        name: 'Northern Arizona University',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwMk1uGQzEViONGPtgHlkKr9Ig_YbIa03P-A&s ',
        youtube: 'http://www.youtube.com/watch?v=A4_mGtb379E ',
        location: 'Flagstaff, Arizona, USA',
        website: 'https://www.nau.edu',
      },
      {
        name: 'Northern Kentucky University',
        img: ' https://images.shiksha.com/mediadata/images/1548654591phpXNG90o.jpeg',
        youtube: ' http://www.youtube.com/watch?v=IlAgui_pd80',
        location: 'Highland Heights, Kentucky, USA',
        website: 'https://www.nku.edu',
      },
      {
        name: 'New York Institute of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1537523802phpzlaQPr.jpeg',
        youtube: ' http://www.youtube.com/watch?v=IlAgui_pd80',
        location: 'New York, New York, USA',
        website: 'https://www.nyit.edu',
      },
      {
        name: 'Northwest Missouri State University',
        img: ' https://images.shiksha.com/mediadata/images/1536752418phpc4TS36.jpeg',
        youtube: ' http://www.youtube.com/watch?v=IlAgui_pd80',
        location: 'Maryville, Missouri, USA',
        website: 'https://www.nwmissouri.edu',
      },
      {
        name: 'University of North Dakota',
        img: ' https://cdn.britannica.com/15/153315-050-D44B6A48/Merrifield-Hall-University-of-North-Dakota-Grand.jpg',
        youtube: 'http://www.youtube.com/watch?v=IlAgui_pd80 ',
        location: 'Grand Forks, North Dakota, USA',
        website: 'https://www.und.edu',
      },
      {
        name: 'University of North Alabama',
        img: 'https://www.una.edu/images/shared.png ',
        youtube: ' http://www.youtube.com/watch?v=o26ezKHDFcg',
        location: 'Florence, Alabama, USA',
        website: 'https://www.una.edu',
      },
      {
        name: 'University of New Haven',
        img: ' https://images.shiksha.com/mediadata/images/1534510752phpcvnXom_g.jpg9',
        youtube: 'http://www.youtube.com/watch?v=o26ezKHDFcg ',
        location: 'West Haven, Connecticut, USA',
        website: 'https://www.newhaven.edu',
      },
      {
        name: 'Oklahoma City University',
        img: ' https://okc-university.transforms.svdcdn.com/production/Campus-Life/CampusBuildingPhotos-4_2023-09-25-114551_fksb.jpg?w=1958&h=668&auto=compress%2Cformat&fit=min&dm=1697640685&s=a43968b45cc10b91da2c33bf0efa2082',
        youtube: ' http://www.youtube.com/watch?v=N4Boc4Zplfk',
        location: 'Oklahoma City, Oklahoma, USA',
        website: 'https://www.okcu.edu',
      },
      {
        name: 'Pacific Lutheran University',
        img: ' https://www.plu.edu/parentsandfamilies/wp-content/uploads/sites/246/2015/04/visit.jpg',
        youtube: ' http://www.youtube.com/watch?v=v3DRYyHD5_8',
        location: 'Tacoma, Washington, USA',
        website: 'https://www.plu.edu',
      },
      {
        name: 'New York University Tandon School of Engineering',
        img: ' https://assets.collegedunia.com/public/college_data/images/studyabroad/appImage/college_3583_19-16:25_t3.jpeg',
        youtube: 'http://www.youtube.com/watch?v=0CI6G8bHffg ',
        location: 'New York, New York, USA',
        website: 'https://engineering.nyu.edu',
      },
      {
        name: 'University of the Pacific',
        img: ' https://images.shiksha.com/mediadata/images/1540902094phpvfWVfy.jpeg',
        youtube: 'http://www.youtube.com/watch?v=0CI6G8bHffg ',
        location: 'Stockton, California, USA',
        website: 'https://www.pacific.edu',
      },
      {
        name: 'Rochester Institute of Technology',
        img: 'https://www.rit.edu/_assets/images/og-image.jpg ',
        youtube: ' http://www.youtube.com/watch?v=pv8eAcvlMEw',
        location: 'Rochester, New York, USA',
        website: 'https://www.rit.edu',
      },
      {
        name: 'Rider University',
        img: 'https://www.rider.edu/sites/default/files/styles/hero_fg/public/2023-08/052721_campus_03.JPG?h=c74750f6&itok=cHSHwpth ',
        youtube: ' http://www.youtube.com/watch?v=pv8eAcvlMEw',
        location: 'Lawrenceville, New Jersey, USA',
        website: 'https://www.rider.edu',
      },
      {
        name: 'Southern New Hampshire University',
        img: 'https://images.shiksha.com/mediadata/images/1538647808phpQ4EdiG.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=v_aHIv5CTOE',
        location: 'Manchester, New Hampshire, USA',
        website: 'https://www.snhu.edu',
      },
      {
        name: 'Stevens Institute of Technology',
        img: ' https://downloads.ctfassets.net/mviowpldu823/5xAwOISiMuAcUmAsMdYjNG/ac0186e3e5221ebec664d4b5595796ce/2.Where_to_Give.jpg',
        youtube: ' http://www.youtube.com/watch?v=v_aHIv5CTOE',
        location: 'Hoboken, New Jersey, USA',
        website: 'https://www.stevens.edu',
      },
      {
        name: 'University of Southern Maine',
        img: 'https://collegesimply.firebaseapp.com/img/primary/university-of-southern-maine-161554.jpg ',
        youtube: ' http://www.youtube.com/watch?v=k4EDWHz4-OQ',
        location: 'Portland, Maine, USA',
        website: 'https://www.usm.maine.edu',
      },
      {
        name: 'Texas Southern University',
        img: ' https://s3-external-1.amazonaws.com/youvisit-img/Assets/img/locations/108750/1280_profile.jpg?v=1727536213',
        youtube: ' http://www.youtube.com/watch?v=mgTftiNyT_4',
        location: 'Houston, Texas, USA',
        website: 'https://www.tsu.edu',
      },
      {
        name: 'University of Wisconsin-La Crosse',
        img: ' https://www.uwlax.edu/globalassets/home/welcoming/2021-uwl-fall-student-life-buildings-0358.jpg/Large',
        youtube: 'http://www.youtube.com/watch?v=mgTftiNyT_4 ',
        location: 'La Crosse, Wisconsin, USA',
        website: 'https://www.uwlax.edu',
      },
      {
        name: 'Western Kentucky University',
        img: 'https://images.shiksha.com/mediadata/images/1540893150phpPmjfCv.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=5-7oPTT6-oU ',
        location: 'Bowling Green, Kentucky, USA',
        website: 'https://www.wku.edu',
      },
      {
        name: 'Webster University',
        img: ' https://www.webster.edu/.ldp/.private_ldp/a262947/production/master/a74350c8-f6a8-4a19-bc8b-3bb21c5754e4.jpg',
        youtube: ' http://www.youtube.com/watch?v=5-7oPTT6-oU',
        location: 'St. Louis, Missouri, USA',
        website: 'https://www.webster.edu',
      },
      {
        name: 'Webber International University',
        img: ' https://images.shiksha.com/mediadata/images/1417423105phpb6umM9.jpeg',
        youtube: ' http://www.youtube.com/watch?v=5-7oPTT6-oU',
        location: 'Babson Park, Florida, USA',
        website: 'https://www.webber.edu',
      },
    ],
    Canada: [
      {
        name: 'Algonquin College',
        img: ' https://www.algonquincollege.com/public-relations/files/2013/02/front-view-2012-small2.jpg',
        youtube: ' http://www.youtube.com/watch?v=94ZIWMB2vQ0',
        location: 'Ottawa, Ontario, Canada',
        website: 'https://www.algonquincollege.com',
      },
      {
        name: 'Brock University',
        img: 'https://appmsmunifyprod.blob.core.windows.net/docs/files/institution/abdec280-fbbc-404e-bfcd-46fa700ff9f5.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=xdLzjcuSFhU',
        location: 'St. Catharines, Ontario, Canada',
        website: 'https://brocku.ca',
      },
      {
        name: 'Centennial College',
        img: 'https://assets.collegedunia.com/public/college_data/images/studyabroad/appImage/college_113_08-15:53_centinnel-college.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=xdLzjcuSFhU ',
        location: 'Toronto, Ontario, Canada',
        website: 'https://www.centennialcollege.ca',
      },
      {
        name: 'Dalhousie University',
        img: ' https://www.dal.ca/_jcr_content/root/maincontent/main/container_274129951_/image.coreimg.jpeg/1730469126417/henry-hicks-building.jpeg',
        youtube: ' http://www.youtube.com/watch?v=xdLzjcuSFhU',
        location: 'Halifax, Nova Scotia, Canada',
        website: 'https://www.dal.ca',
      },
      {
        name: 'Fairleigh Dickinson University',
        img: ' https://assets.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1585_03-14:55_fairleigh-dickinson-university-21.jpeg',
        youtube: ' http://www.youtube.com/watch?v=yfvcda7_EiA',
        location: 'Vancouver, British Columbia, Canada',
        website: 'https://www.fdu.edu',
      },
      {
        name: 'George Brown College',
        img: ' https://images.shiksha.com/mediadata/images/1586241599php82HByr_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=e4W8HkINzxs',
        location: 'Toronto, Ontario, Canada',
        website: 'https://www.georgebrown.ca',
      },
      {
        name: 'Georgian College',
        img: ' https://www.georgiancollege.ca/wp-content/uploads/Georgian-College-South-Georgian-Bay-Campus-in-the-fall-1.jpg',
        youtube: ' http://www.youtube.com/watch?v=EDiiU5n7tS4',
        location: 'Barrie, Ontario, Canada',
        website: 'https://www.georgiancollege.ca',
      },
      {
        name: 'Humber College',
        img: ' https://images.shiksha.com/mediadata/images/1533646941phpOojdGB.jpeg',
        youtube: ' http://www.youtube.com/watch?v=Zan3PXgaJsA',
        location: 'Toronto, Ontario, Canada',
        website: 'https://humber.ca',
      },
      {
        name: 'Mount Allison University',
        img: ' https://cuebc.org/wp-content/uploads/2020/09/cover-Mount-Allison-University.jpg',
        youtube: 'http://www.youtube.com/watch?v=Cw3X4cBCVbs ',
        location: 'Sackville, New Brunswick, Canada',
        website: 'https://www.mta.ca',
      },
      {
        name: 'Niagara College',
        img: ' https://www.niagaracollege.ca/wp-content/uploads/2024/08/banner-welland-2024.jpg',
        youtube: ' http://www.youtube.com/watch?v=lvoiNC6udoQ',
        location: 'Welland, Ontario, Canada',
        website: 'https://www.niagaracollege.ca',
      },
      {
        name: 'Sheridan College',
        img: 'https://images.shiksha.com/mediadata/images/1533032515phptEH0Ge.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=V1SbPLCIA4k',
        location: 'Oakville, Ontario, Canada',
        website: 'https://www.sheridancollege.ca',
      },
      {
        name: 'Seneca College',
        img: ' https://polytechnicscanada.ca/wp-content/uploads/2021/02/Seneca-4.png',
        youtube: ' http://www.youtube.com/watch?v=pli66J6pOy8',
        location: 'Toronto, Ontario, Canada',
        website: 'https://www.senecacollege.ca',
      },
      {
        name: 'Saskatchewan Polytechnic',
        img: ' https://images.shiksha.com/mediadata/images/1499334146phpYXxEMq_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=AOyj-AbsRio',
        location: 'Saskatchewan, Canada',
        website: 'https://saskpolytech.ca',
      },
      {
        name: 'Okanagan College',
        img: ' https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/CH/myhc_343791.jpg',
        youtube: 'http://www.youtube.com/watch?v=NvzGxNb7TSM ',
        location: 'Kelowna, British Columbia, Canada',
        website: 'https://www.okanagan.bc.ca',
      },
      {
        name: 'Thompson Rivers University',
        img: ' https://images.shiksha.com/mediadata/images/1533105684phpWW5jsZ.jpeg',
        youtube: ' http://www.youtube.com/watch?v=6jc9QVVUC8Q',
        location: 'Kamloops, British Columbia, Canada',
        website: 'https://www.tru.ca',
      },
      {
        name: 'Laurentian University',
        img: 'https://images.shiksha.com/mediadata/images/1537264772php506TJF_g.jpg ',
        youtube: ' http://www.youtube.com/watch?v=TGAFuSHZa1E',
        location: 'Sudbury, Ontario, Canada',
        website: 'https://laurentian.ca',
      },
      {
        name: 'University of Regina',
        img: ' https://collegekampus.com/wp-content/uploads/2020/02/University-of-Regina.jpg',
        youtube: ' http://www.youtube.com/watch?v=vzoQq252sJA',
        location: 'Regina, Saskatchewan, Canada',
        website: 'https://www.uregina.ca',
      },
      {
        name: 'Royal Roads University',
        img: ' https://images.shiksha.com/mediadata/images/1534842387phphdfhwd.jpeg',
        youtube: 'http://www.youtube.com/watch?v=5QYpyjb8UJI ',
        location: 'Victoria, British Columbia, Canada',
        website: 'https://www.royalroads.ca',
      },
      {
        name: 'Trent University',
        img: ' https://images.shiksha.com/mediadata/images/1537356102php0pdMGX.jpeg',
        youtube: ' http://www.youtube.com/watch?v=j5EojL1-xVY',
        location: 'Peterborough, Ontario, Canada',
        website: 'https://www.trentu.ca',
      },
      {
        name: 'University Canada West',
        img: ' https://images.shiksha.com/mediadata/images/1685596752phpyZbZbS.jpeg',
        youtube: 'http://www.youtube.com/watch?v=EoqSa_opeck ',
        location: 'Vancouver, British Columbia, Canada',
        website: 'https://www.ucanwest.ca',
      },
      {
        name: 'University of Prince Edward Island',
        img: ' https://images.shiksha.com/mediadata/images/1504245848php4uKv8g.jpeg',
        youtube: ' http://www.youtube.com/watch?v=0MdNm-75rdM',
        location: 'Charlottetown, Prince Edward Island, Canada',
        website: 'https://www.upei.ca',
      },
      {
        name: 'University of the Fraser Valley',
        img: 'https://images.shiksha.com/mediadata/images/1534398757phpcLoH6a.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=C_fkv85M1Bo',
        location: 'Abbotsford, British Columbia, Canada',
        website: 'https://www.ufv.ca',
      },
    ],

    Australia: [
      {
        name: 'Australian National University',
        img: 'https://didmdw8v48h5q.cloudfront.net/wp-content/uploads/2021/11/australian-national-university.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=anv0XrLhg5Y',
        location: 'Canberra, Australia',
        website: 'https://www.anu.edu.au',
      },
      {
        name: 'University of Adelaide',
        img: ' https://images.shiksha.com/mediadata/images/1507613211phpOfXXhe_g.jpg',
        youtube: 'http://www.youtube.com/watch?v=X__i5yTa7yE ',
        location: 'Adelaide, Australia',
        website: 'https://www.adelaide.edu.au',
      },
      {
        name: 'Bond University',
        img: ' https://www.google.com/url?sa=i&url=https%3A%2F%2Fbond.edu.au%2F&psig=AOvVaw2tThSe5ztGKkZZSFM7375A&ust=1738506877966000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIjdpPrYoosDFQAAAAAdAAAAABAE',
        youtube: 'http://www.youtube.com/watch?v=JynvFXYnjXU ',
        location: 'Robina, Queensland, Australia',
        website: 'https://bond.edu.au',
      },
      {
        name: 'Federation University Australia',
        img: ' https://images.shiksha.com/mediadata/images/1537330381phpthrLPp.png',
        youtube: 'http://www.youtube.com/watch?v=0IDK-KbJPRg ',
        location: 'Ballarat, Victoria, Australia',
        website: 'https://federation.edu.au',
      },
      {
        name: 'Box Hill Institute',
        img: 'https://www.datocms-assets.com/6783/1553648199-img0286.jpg ',
        youtube: 'http://www.youtube.com/watch?v=BuwNGWVMZfU ',
        location: 'Box Hill, Victoria, Australia',
        website: 'https://www.boxhill.edu.au',
      },
      {
        name: 'CQUniversity',
        img: ' https://images.shiksha.com/mediadata/images/1535095138phpN2utER_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=aDn6ngUJYbo',
        location: 'Rockhampton, Queensland, Australia',
        website: 'https://www.cqu.edu.au',
      },
      {
        name: 'Charles Darwin University',
        img: ' https://images.shiksha.com/mediadata/images/1585746311phpj8hXy0.jpeg',
        youtube: 'http://www.youtube.com/watch?v=1Mqe3g4yiFQ ',
        location: 'Darwin, Northern Territory, Australia',
        website: 'https://www.cdu.edu.au',
      },
      {
        name: 'Curtin University',
        img: ' https://images.shiksha.com/mediadata/images/1496824636phpz3FH7X.jpeg',
        youtube: ' http://www.youtube.com/watch?v=E_HX6lhtXY4',
        location: 'Perth, Western Australia, Australia',
        website: 'https://www.curtin.edu.au',
      },
      {
        name: 'Griffith University',
        img: ' https://static.sliit.lk/wp-content/uploads/2017/12/sliit-international-section-transfer-options-Griffith-university.jpg',
        youtube: ' http://www.youtube.com/watch?v=wEpeW8T6LCE',
        location: 'Queensland, Australia',
        website: 'https://www.griffith.edu.au',
      },
      {
        name: 'James Cook University',
        img: ' https://images.shiksha.com/mediadata/images/1499948698phpvKoAxZ.jpeg',
        youtube: 'http://www.youtube.com/watch?v=JjR4aQtISQM ',
        location: 'Townsville, Queensland, Australia',
        website: 'https://www.jcu.edu.au',
      },
      {
        name: 'La Trobe University',
        img: ' https://www.latrobe.edu.au/about/rankings-and-ratings/ds-images/LTU_Media_16077_1700.jpg',
        youtube: ' http://www.youtube.com/watch?v=Qm6zsZeIjTw',
        location: 'Melbourne, Victoria, Australia',
        website: 'https://www.latrobe.edu.au',
      },
      {
        name: 'Murdoch University',
        img: 'https://www.nimsuniversity.org/images/university/university-banner-3.webp ',
        youtube: ' http://www.youtube.com/watch?v=AM61zHUL5Dg',
        location: 'Perth, Western Australia, Australia',
        website: 'https://www.murdoch.edu.au',
      },
      {
        name: 'Monash University',
        img: ' https://www.monash.edu/__data/assets/image/0004/959530/clayton-campus-new-horizons-building-exterior-at-night-2013.jpg',
        youtube: ' http://www.youtube.com/watch?v=969i7d4g_ZE',
        location: 'Melbourne, Victoria, Australia',
        website: 'https://www.monash.edu',
      },
      {
        name: 'University of Melbourne',
        img: ' https://images.shiksha.com/mediadata/images/1539748284phpkXrez1.jpeg',
        youtube: 'http://www.youtube.com/watch?v=yeOSS8M-QaQ ',
        location: 'Melbourne, Victoria, Australia',
        website: 'https://www.unimelb.edu.au',
      },
      {
        name: 'Queensland University of Technology',
        img: 'https://images.shiksha.com/mediadata/images/1688454409phprCSiM9.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=MNhZUVfy5HM',
        location: 'Brisbane, Queensland, Australia',
        website: 'https://www.qut.edu.au',
      },
      {
        name: 'RMIT University',
        img: 'https://images.shiksha.com/mediadata/images/1533809674phpSjXxio_g.jpg ',
        youtube: 'http://www.youtube.com/watch?v=sovjfABcx9s ',
        location: 'Melbourne, Victoria, Australia',
        website: 'https://www.rmit.edu.au',
      },
      {
        name: 'Swinburne University of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1539258560phpv7wJ3h.jpeg',
        youtube: ' http://www.youtube.com/watch?v=fUx1DDUPHVs',
        location: 'Melbourne, Victoria, Australia',
        website: 'https://www.swinburne.edu.au',
      },
      {
        name: 'University of Southern Queensland',
        img: ' https://images.shiksha.com/mediadata/images/1537336589php2je4Zp.jpeg',
        youtube: ' http://www.youtube.com/watch?v=OF-wX3nrm84',
        location: 'Toowoomba, Queensland, Australia',
        website: 'https://www.usq.edu.au',
      },
      {
        name: 'University of Sydney',
        img: 'https://images.shiksha.com/mediadata/images/1515481785phpZsgL9D_g.png ',
        youtube: ' http://www.youtube.com/watch?v=wuUK-mmpiZY',
        location: 'Sydney, New South Wales, Australia',
        website: 'https://www.sydney.edu.au',
      },
      {
        name: 'University of Tasmania',
        img: ' https://images.shiksha.com/mediadata/images/1535441166php9jbL2s.jpeg',
        youtube: 'http://www.youtube.com/watch?v=hIr7Ya0PaO4 ',
        location: 'Hobart, Tasmania, Australia',
        website: 'https://www.utas.edu.au',
      },
      {
        name: 'University of Technology Sydney',
        img: ' https://universitiesaustralia.edu.au/wp-content/uploads/2019/06/UTS-2020_Web-1-1333x1000.jpg',
        youtube: ' http://www.youtube.com/watch?v=KlvrPTfDqZQ',
        location: 'Sydney, New South Wales, Australia',
        website: 'https://www.uts.edu.au',
      },
      {
        name: 'Victoria University',
        img: 'https://universitiesaustralia.edu.au/wp-content/uploads/2019/06/vu-city-campus-landscape-web-1400x933.jpg ',
        youtube: 'http://www.youtube.com/watch?v=TguUTzyZj7c ',
        location: 'Melbourne, Victoria, Australia',
        website: 'https://www.vu.edu.au',
      },
      {
        name: 'University of Western Australia',
        img: 'https://images.shiksha.com/mediadata/images/1541403097phplpDP5l.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=2Q8nPJ2P4ZA',
        location: 'Perth, Western Australia, Australia',
        website: 'https://www.uwa.edu.au',
      },
      {
        name: 'University of Wollongong',
        img: 'https://onesim-production.s3.ap-southeast-1.amazonaws.com/onesim/media/ge-uni-of-wollongong/wollongong-details-d.jpg?ext=.jpg ',
        youtube: 'https://youtu.be/RRpS6V-fDEo ',
        location: 'Wollongong, New South Wales, Australia',
        website: 'https://www.uow.edu.au',
      },
      {
        name: 'Western Sydney University',
        img: 'https://images.shiksha.com/mediadata/images/1533896110phpf1Qvb0.jpeg ',
        youtube: 'https://youtu.be/0nzXAEXMZC4?si=c4nHyPeVI7ih6LrE ',
        location: 'Sydney, New South Wales, Australia',
        website: 'https://www.westernsydney.edu.au',
      },
    ],

    NewZealand: [
      {
        name: 'Auckland University of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1562658850phpjXQyvg.jpeg',
        youtube: ' http://www.youtube.com/watch?v=9-5qGJWkqrM',
        location: 'Auckland, New Zealand',
        website: 'https://www.aut.ac.nz',
      },
      {
        name: 'University of Auckland',
        img: ' https://images.shiksha.com/mediadata/images/1533708768phpvTZAqF_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=Di0mvQAX8dE',
        location: 'Auckland, New Zealand',
        website: 'https://www.auckland.ac.nz',
      },
      {
        name: 'AIS St Helens',
        img: ' https://images.shiksha.com/mediadata/images/1540984580phptmqCZE_g.jpg',
        youtube: 'http://www.youtube.com/watch?v=C5NpvFEUyfs ',
        location: 'Auckland, New Zealand',
        website: 'https://www.ais.ac.nz',
      },
      {
        name: 'University of Canterbury',
        img: ' https://appmsmunifyprod.blob.core.windows.net/docs/files/institution/bc1276b9-2e2e-4811-b317-2c4b5659bd09.jpeg',
        youtube: ' http://www.youtube.com/watch?v=3GDUhDwi98g',
        location: 'Christchurch, New Zealand',
        website: 'https://www.canterbury.ac.nz',
      },
      {
        name: 'Ara Institute of Canterbury',
        img: ' https://images.shiksha.com/mediadata/images/1540208681phpF0U3BD.jpeg',
        youtube: ' http://www.youtube.com/watch?v=0PP0m-k_RsQ',
        location: 'Christchurch, New Zealand',
        website: 'https://www.ara.ac.nz',
      },
      {
        name: 'Eastern Institute of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1499170304phpfSBvez.jpeg',
        youtube: ' http://www.youtube.com/watch?v=CwvNVkzYIZI',
        location: "Hawke's Bay, New Zealand",
        website: 'https://www.eit.ac.nz',
      },
      {
        name: 'Lincoln University',
        img: ' https://lincolnshire.org/wp-content/uploads/2013/01/lincoln-university.webp',
        youtube: ' http://www.youtube.com/watch?v=4aset4B1CE8',
        location: 'Lincoln, New Zealand',
        website: 'https://www.lincoln.ac.nz',
      },
      {
        name: 'Lifeway College',
        img: ' https://images.shiksha.com/mediadata/images/1540811849php0QYgA0_210x157.jpg',
        youtube: ' http://www.youtube.com/watch?v=W881dylZLn8',
        location: 'Snells Beach, New Zealand',
        website: 'https://www.lifeway.ac.nz',
      },
      {
        name: 'Manukau Institute of Technology',
        img: 'https://images.shiksha.com/mediadata/images/1538125521phpTaCkJ1.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=osSKiwbI3_8',
        location: 'Auckland, New Zealand',
        website: 'https://www.manukau.ac.nz',
      },
      {
        name: 'Massey University',
        img: ' https://images.shiksha.com/mediadata/images/1535363251phpo8F5o9.png',
        youtube: 'http://www.youtube.com/watch?v=IKfEe207pLQ ',
        location: 'Palmerston North, New Zealand',
        website: 'https://www.massey.ac.nz',
      },
      {
        name: 'North Shore International Academy',
        img: 'https://images.shiksha.com/mediadata/images/1492497384phpJk6AtI.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=aBmeoLLlm20',
        location: 'Auckland, New Zealand',
        website: 'https://www.nsia.co.nz',
      },
      {
        name: 'University of Otago',
        img: ' https://images.shiksha.com/mediadata/images/1534392340phpM98iUm.jpeg',
        youtube: 'http://www.youtube.com/watch?v=97hq9hrzXDU ',
        location: 'Dunedin, New Zealand',
        website: 'https://www.otago.ac.nz',
      },
      {
        name: 'Unitec Institute of Technology',
        img: 'https://images.shiksha.com/mediadata/images/1540294423php3f4PZZ.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=26oJh9RxPCk ',
        location: 'Auckland, New Zealand',
        website: 'https://www.unitec.ac.nz',
      },
      {
        name: 'Victoria University of Wellington',
        img: 'https://images.shiksha.com/mediadata/images/1539329693phpfQCotj.jpeg ',
        youtube: 'http://www.youtube.com/watch?v=w0jHORkhlmI ',
        location: 'Wellington, New Zealand',
        website: 'https://www.wgtn.ac.nz',
      },
      {
        name: 'Toi Ohomai Institute of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1540381213phpIDYAku.jpeg',
        youtube: 'http://www.youtube.com/watch?v=mc22n1x8v_0 ',
        location: 'Rotorua, New Zealand',
        website: 'https://www.toiohomai.ac.nz',
      },
      {
        name: 'Wellington Institute of Technology',
        img: 'https://myglobaluni.com/public/storage/university/sF0jbeaVBNVH8rLeTJFFuF004VLu9KQDHYTmB4Jx.jpg ',
        youtube: ' http://www.youtube.com/watch?v=Q7HpFGRUFRo',
        location: 'Wellington, New Zealand',
        website: 'https://www.weltec.ac.nz',
      },
      {
        name: 'University of Waikato',
        img: 'https://images.shiksha.com/mediadata/images/1537355426php7kBe0K.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=ZjiJFki1fhM',
        location: 'Hamilton, New Zealand',
        website: 'https://www.waikato.ac.nz',
      },
      {
        name: 'Whitireia New Zealand',
        img: 'https://images.shiksha.com/mediadata/images/1541130911phpPei0KK.jpeg ',
        youtube: ' http://www.youtube.com/watch?v=rphckBQDZQw',
        location: 'Porirua, New Zealand',
        website: 'https://www.whitireia.ac.nz',
      },
      {
        name: 'Pacific International Hotel Management School',
        img: 'https://edysor.in/images/university/banner/Pacific-International-Hotel-Management-School.webp ',
        youtube: ' http://www.youtube.com/watch?v=MFhDkYOB2JE',
        location: 'New Plymouth, New Zealand',
        website: 'https://www.pihms.ac.nz',
      },
    ],
    Ireland: [
      {
        name: 'University College Dublin',
        img: 'https://www.smurfitschool.ie/t4media/QS%20rankings.png ',
        youtube: ' http://www.youtube.com/watch?v=5IYL1y9IWd0',
        location: 'Dublin, Ireland',
        website: 'https://www.ucd.ie',
      },
      {
        name: 'Maynooth University',
        img: ' https://edysor.in/images/university/banner/Maynooth-University4837c5ba243d5faa.webp',
        youtube: ' http://www.youtube.com/watch?v=1UseKXoyWEw',
        location: 'Maynooth, Ireland',
        website: 'https://www.maynoothuniversity.ie',
      },
      {
        name: 'Dublin City University',
        img: ' https://images.shiksha.com/mediadata/images/1536667121phpWIKpkF.jpeg',
        youtube: ' http://www.youtube.com/watch?v=U9u957E-PO8',
        location: 'Dublin, Ireland',
        website: 'https://www.dcu.ie',
      },
      {
        name: 'University of Limerick',
        img: ' https://admitx.in/wp-content/uploads/2024/07/University-of-Limerick.webp',
        youtube: 'http://www.youtube.com/watch?v=Vg789B23vxU ',
        location: 'Limerick, Ireland',
        website: 'https://www.ul.ie',
      },
      {
        name: 'National University of Ireland, Galway',
        img: ' https://images.shiksha.com/mediadata/images/1664883749phpmwMWmw_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=VGLdCQy3SPQ',
        location: 'Galway, Ireland',
        website: 'https://www.nuigalway.ie',
      },
      {
        name: 'University College Cork',
        img: ' https://images.shiksha.com/mediadata/images/1644382168phpdYUqY3.jpeg',
        youtube: 'http://www.youtube.com/watch?v=c6UfAWW2bC8 ',
        location: 'Cork, Ireland',
        website: 'https://www.ucc.ie',
      },
      {
        name: 'Technological University Dublin',
        img: ' https://universityvacancies.com/sites/default/files/main_image_0.jpg',
        youtube: ' http://www.youtube.com/watch?v=Fzb48bUvDSk',
        location: 'Dublin, Ireland',
        website: 'https://www.tudublin.ie',
      },
      {
        name: 'Dundalk Institute of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1577779242phpdY7no9.jpeg',
        youtube: ' http://www.youtube.com/watch?v=gcqK7UgWI80',
        location: 'Dundalk, Ireland',
        website: 'https://www.dkit.ie',
      },
      {
        name: 'Munster Technological University',
        img: 'https://uniabroad.io/storage/featuredImage/1673069201-banner-Munster%20Technological%20University.webp ',
        youtube: 'http://www.youtube.com/watch?v=2E3JizWXFH8',
        location: 'Cork, Ireland',
        website: 'https://www.mtu.ie',
      },
      {
        name: 'Waterford Institute of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1540551194phpsIq9O1.jpeg',
        youtube: ' http://www.youtube.com/watch?v=AUrbWonSso4 ',
        location: 'Waterford, Ireland',
        website: 'https://www.wit.ie',
      },
      {
        name: 'National College of Ireland',
        img: ' https://images.shiksha.com/mediadata/images/1410162026phpBNsmI0.jpeg',
        youtube: 'http://www.youtube.com/watch?v=eEg60WLUVa0 ',
        location: 'Dublin, Ireland',
        website: 'https://www.ncirl.ie',
      },
      {
        name: 'Dublin Business School',
        img: ' https://images.shiksha.com/mediadata/images/1505732463phpmZ1Jty_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=ad4YRuuAz3M',
        location: 'Dublin, Ireland',
        website: 'https://www.dbs.ie',
      },
    ],
    Germany: [
      {
        name: 'Ludwig Maximilian University of Munich',
        img: 'https://image-static.collegedunia.com/public/college_data/images/studyabroad/appImage/college_690_14-16:11_cov.jpeg?h=185&w=375&mode=stretch ',
        youtube: ' http://www.youtube.com/watch?v=flbn_DmnRNM',
        location: 'Munich, Germany',
        website: 'https://www.lmu.de',
      },
      {
        name: 'Technical University of Munich',
        img: ' https://images.shiksha.com/mediadata/images/1533559592phpsYF8Oy.jpeg',
        youtube: ' http://www.youtube.com/watch?v=0MqGXCAaMdc',
        location: 'Munich, Germany',
        website: 'https://www.tum.de',
      },
      {
        name: 'Heidelberg University',
        img: ' https://www.heidelberg.edu/sites/default/files/styles/large/public/2021-03/admission%20%2810%29.jpg?itok=Ez9LmEai',
        youtube: ' http://www.youtube.com/watch?v=wJ3eqaoz7k4',
        location: 'Heidelberg, Germany',
        website: 'https://www.uni-heidelberg.de',
      },
      {
        name: 'Humboldt University of Berlin',
        img: ' https://images.shiksha.com/mediadata/images/1534925114phpHWONUz.jpeg',
        youtube: 'http://www.youtube.com/watch?v=yAU87wa5PkA ',
        location: 'Berlin, Germany',
        website: 'https://www.hu-berlin.de',
      },

      //////////////////////////////////////////////////////////////////////////////////////////////////////////////
      {
        name: 'Free University of Berlin',
        img: ' https://assets.collegedunia.com/public/college_data/images/studyabroad/appImage/college_631_24-15:08_f1.jpeg',
        youtube: ' http://www.youtube.com/watch?v=06zHXOz8e_o',
        location: 'Berlin, Germany',
        website: 'https://www.fu-berlin.de',
      },
      {
        name: 'University of Göttingen',
        img: 'https://prins.uni-goettingen.de/files/bilder/pic_679fb721e320250123095701.jpg ',
        youtube: ' http://www.youtube.com/watch?v=xWD4QD7tr9Y',
        location: 'Göttingen, Germany',
        website: 'https://www.uni-goettingen.de',
      },
      {
        name: 'RWTH Aachen University',
        img: 'https://www.rwth-aachen.de/global/show_picture.asp?id=aaaaaaaabokyknh&w2=1080&h2=719&clip=center,1080,719&q=73 ',
        youtube: ' http://www.youtube.com/watch?v=EoobdaJ3_Ic',
        location: 'Aachen, Germany',
        website: 'https://www.rwth-aachen.de',
      },
      {
        name: 'University of Freiburg',
        img: 'https://uni-freiburg.de/en/wp-content/uploads/sites/61/institutsviertel-universitaet-freiburg-sandra-meyndt.jpg ',
        youtube: 'http://www.youtube.com/watch?v=7apmBol9f2w ',
        location: 'Freiburg, Germany',
        website: 'https://www.uni-freiburg.de',
      },
      {
        name: 'University of Stuttgart',
        img: ' https://www.studying-in-germany.org/wp-content/uploads/2020/01/stuttgart.jpg',
        youtube: 'http://www.youtube.com/watch?v=HweJC46q-Sg ',
        location: 'Stuttgart, Germany',
        website: 'https://www.uni-stuttgart.de',
      },
      {
        name: 'Karlsruhe Institute of Technology',
        img: ' https://images.shiksha.com/mediadata/images/1535442840php6iuI85_g.jpg',
        youtube: ' http://www.youtube.com/watch?v=qqS1hqZo_J4',
        location: 'Karlsruhe, Germany',
        website: 'https://www.kit.edu',
      },
    ],
  };

  try {
    for (const [country, colleges] of Object.entries(CollegeData)) {
      await setDoc(doc(db, 'college', country), { colleges });
      console.log(`Added data for ${country}`);
    }
    console.log('All data added successfully!');
  } catch (error) {
    console.error('Error adding data:', error);
  }
};
