export const CollegeData = {
UK : [
    { img:'https://www.britishcouncil.or.th/sites/default/files/anglia_ruskin_university.jpg',name: "Anglia Ruskin University", location: "Cambridge, England", website: "https://aru.ac.uk" },
    { img:'https://www.thecompleteuniversityguide.co.uk/commimg-cug/myhotcourses/institution/profile/image/myhc_327725_1106px.jpg', name: "Bangor University", location: "Bangor, Wales", website: "https://www.bangor.ac.uk" },
    { name: "Birkbeck University of London", location: "London, England", website: "https://www.bbk.ac.uk" },
    { name: "Birmingham City University", location: "Birmingham, England", website: "https://www.bcu.ac.uk" },
    { name: "Bournemouth University", location: "Bournemouth, England", website: "https://www.bournemouth.ac.uk" },
    { name: "Brunel University", location: "London, England", website: "https://www.brunel.ac.uk" },
    { name: "Cardiff University", location: "Cardiff, Wales", website: "https://www.cardiff.ac.uk" },
    { name: "City University London", location: "London, England", website: "https://www.city.ac.uk" },
    { name: "Coventry University", location: "Coventry, England", website: "https://www.coventry.ac.uk" },
    { name: "De Montfort University", location: "Leicester, England", website: "https://www.dmu.ac.uk" },
    { name: "Durham University", location: "Durham, England", website: "https://www.durham.ac.uk" },
    { name: "Edinburgh Napier University", location: "Edinburgh, Scotland", website: "https://www.napier.ac.uk" },
    { name: "Glasgow Caledonian University", location: "Glasgow, Scotland", website: "https://www.gcu.ac.uk" },
    { name: "Goldsmiths University of London", location: "London, England", website: "https://www.gold.ac.uk" },
    { name: "Heriot-Watt University", location: "Edinburgh, Scotland", website: "https://www.hw.ac.uk" },
    { name: "Kingston University", location: "Kingston upon Thames, England", website: "https://www.kingston.ac.uk" },
    { name: "Leeds Beckett University", location: "Leeds, England", website: "https://www.leedsbeckett.ac.uk" },
    { name: "University of Lincoln", location: "Lincoln, England", website: "https://www.lincoln.ac.uk" },
    { name: "London Metropolitan University", location: "London, England", website: "https://www.londonmet.ac.uk" },
    { name: "London South Bank University", location: "London, England", website: "https://www.lsbu.ac.uk" },
    { name: "Loughborough University", location: "Loughborough, England", website: "https://www.lboro.ac.uk" },
    { name: "Middlesex University", location: "London, England", website: "https://www.mdx.ac.uk" },
    { name: "Newcastle University", location: "Newcastle upon Tyne, England", website: "https://www.ncl.ac.uk" },
    { name: "Northumbria University", location: "Newcastle upon Tyne, England", website: "https://www.northumbria.ac.uk" },
    { name: "Nottingham Trent University", location: "Nottingham, England", website: "https://www.ntu.ac.uk" },
    { name: "Oxford Brookes University", location: "Oxford, England", website: "https://www.brookes.ac.uk" },
    { name: "Queen Mary University of London", location: "London, England", website: "https://www.qmul.ac.uk" },
    { name: "Queen's University Belfast", location: "Belfast, Northern Ireland", website: "https://www.qub.ac.uk" },
    { name: "Robert Gordon University", location: "Aberdeen, Scotland", website: "https://www.rgu.ac.uk" },
    { name: "Royal Holloway University of London", location: "Egham, England", website: "https://www.royalholloway.ac.uk" },
    { name: "SOAS University of London", location: "London, England", website: "https://www.soas.ac.uk" },
    { name: "Sheffield Hallam University", location: "Sheffield, England", website: "https://www.shu.ac.uk" },
    { name: "Solent University", location: "Southampton, England", website: "https://www.solent.ac.uk" },
    { name: "Swansea University", location: "Swansea, Wales", website: "https://www.swansea.ac.uk" },
    { name: "Teesside University", location: "Middlesbrough, England", website: "https://www.tees.ac.uk" },
    { name: "The University of Edinburgh", location: "Edinburgh, Scotland", website: "https://www.ed.ac.uk" },
    { name: "The University of Nottingham", location: "Nottingham, England", website: "https://www.nottingham.ac.uk" },
    { name: "The University of Sheffield", location: "Sheffield, England", website: "https://www.sheffield.ac.uk" },
    { name: "University for the Creative Arts (UCA)", location: "Farnham, England", website: "https://www.uca.ac.uk" },
    { name: "University of Bedfordshire", location: "Luton, England", website: "https://www.beds.ac.uk" },
    { name: "University of Bolton", location: "Bolton, England", website: "https://www.bolton.ac.uk" },
    { name: "University of Brighton", location: "Brighton, England", website: "https://www.brighton.ac.uk" },
    { name: "University of Central Lancashire", location: "Preston, England", website: "https://www.uclan.ac.uk" },
    { name: "University of Dundee", location: "Dundee, Scotland", website: "https://www.dundee.ac.uk" },
    { name: "University of East Anglia", location: "Norwich, England", website: "https://www.uea.ac.uk" },
    { name: "University of East London", location: "London, England", website: "https://www.uel.ac.uk" },
    { name: "University of Essex", location: "Colchester, England", website: "https://www.essex.ac.uk" },
    { name: "University of Exeter", location: "Exeter, England", website: "https://www.exeter.ac.uk" },
    { name: "University of Glasgow", location: "Glasgow, Scotland", website: "https://www.gla.ac.uk" },
    { name: "University of Greenwich", location: "London, England", website: "https://www.gre.ac.uk" },
    { name: "University of Hertfordshire", location: "Hatfield, England", website: "https://www.herts.ac.uk" },
    { name: "University of Huddersfield", location: "Huddersfield, England", website: "https://www.hud.ac.uk" },
    { name: "University of Kent", location: "Canterbury, England", website: "https://www.kent.ac.uk" },
    { name: "University of Leicester", location: "Leicester, England", website: "https://le.ac.uk" },
    { name: "University of Liverpool", location: "Liverpool, England", website: "https://www.liverpool.ac.uk" },
    { name: "University of Northampton", location: "Northampton, England", website: "https://www.northampton.ac.uk" },
    { name: "University of Plymouth", location: "Plymouth, England", website: "https://www.plymouth.ac.uk" },
    { name: "University of Portsmouth", location: "Portsmouth, England", website: "https://www.port.ac.uk" },
    { name: "University of Reading", location: "Reading, England", website: "https://www.reading.ac.uk" },
    { name: "University of Roehampton", location: "London, England", website: "https://www.roehampton.ac.uk" },
    { name: "University of Salford", location: "Salford, England", website: "https://www.salford.ac.uk" },
    { name: "University of Southampton", location: "Southampton, England", website: "https://www.southampton.ac.uk" },
    { name: "University of Stirling", location: "Stirling, Scotland", website: "https://www.stir.ac.uk" },
    { name: "University of Strathclyde", location: "Glasgow, Scotland", website: "https://www.strath.ac.uk" },
    { name: "University of Surrey", location: "Guildford, England", website: "https://www.surrey.ac.uk" },
    { name: "University of Sussex", location: "Brighton, England", website: "https://www.sussex.ac.uk" },
    { name: "Ulster University", location: "Northern Ireland", website: "https://www.ulster.ac.uk" },
    { name: "University of the West of England", location: "Bristol, England", website: "https://www.uwe.ac.uk" },
    { name: "University of Warwick", location: "Coventry, England", website: "https://warwick.ac.uk" },
    { name: "University of Westminster", location: "London, England", website: "https://www.westminster.ac.uk" },
    { name: "University of Wolverhampton", location: "Wolverhampton, England", website: "https://www.wlv.ac.uk" },
    { name: "University of York", location: "York, England", website: "https://www.york.ac.uk" }
  ],
  USA: [
    { name: "University of Alabama", location: "Alabama, USA", website: "https://www.ua.edu" },
    { name: "University of Bridgeport", location: "Bridgeport, Connecticut, USA", website: "https://www.bridgeport.edu" },
    { name: "Arkansas State University", location: "Jonesboro, Arkansas, USA", website: "https://www.astate.edu" },
    { name: "California State University San Marcos", location: "San Marcos, California, USA", website: "https://www.csusm.edu" },
    { name: "California State University San Bernardino", location: "San Bernardino, California, USA", website: "https://www.csusb.edu" },
    { name: "California State University Stanislaus", location: "Turlock, California, USA", website: "https://www.csustan.edu" },
    { name: "Clarkson University", location: "Potsdam, New York, USA", website: "https://www.clarkson.edu" },
    { name: "Dallas Baptist University", location: "Dallas, Texas, USA", website: "https://www.dbu.edu" },
    { name: "Florida International University", location: "Miami, Florida, USA", website: "https://www.fiu.edu" },
    { name: "Florida Institute of Technology", location: "Melbourne, Florida, USA", website: "https://www.fit.edu" },
    { name: "Grand Valley State University", location: "Allendale, Michigan, USA", website: "https://www.gvsu.edu" },
    { name: "Globe University", location: "Various Locations, USA", website: "https://www.globeuniversity.edu" },
    { name: "Hamline University", location: "Saint Paul, Minnesota, USA", website: "https://www.hamline.edu" },
    { name: "Indiana State University", location: "Terre Haute, Indiana, USA", website: "https://www.indstate.edu" },
    { name: "International Technological University", location: "Santa Clara, California, USA", website: "https://www.itu.edu" },
    { name: "James Madison University", location: "Harrisonburg, Virginia, USA", website: "https://www.jmu.edu" },
    { name: "Jacksonville University", location: "Jacksonville, Florida, USA", website: "https://www.ju.edu" },
    { name: "Kansas State University", location: "Manhattan, Kansas, USA", website: "https://www.k-state.edu" },
    { name: "Kent State University", location: "Kent, Ohio, USA", website: "https://www.kent.edu" },
    { name: "Liberty University", location: "Lynchburg, Virginia, USA", website: "https://www.liberty.edu" },
    { name: "La Salle University", location: "Philadelphia, Pennsylvania, USA", website: "https://www.lasalle.edu" },
    { name: "Midwestern State University", location: "Wichita Falls, Texas, USA", website: "https://www.msutexas.edu" },
    { name: "Manhattan Institute of Management", location: "New York, USA", website: "https://www.mimusa.edu" },
    { name: "Missouri University of Science and Technology", location: "Rolla, Missouri, USA", website: "https://www.mst.edu" },
    { name: "Mountain State University", location: "Beckley, West Virginia, USA", website: "https://www.mountainstate.edu" },
    { name: "University of Massachusetts Boston", location: "Boston, Massachusetts, USA", website: "https://www.umb.edu" },
    { name: "University of Massachusetts Lowell", location: "Lowell, Massachusetts, USA", website: "https://www.uml.edu" },
    { name: "University of Massachusetts Dartmouth", location: "Dartmouth, Massachusetts, USA", website: "https://www.umassd.edu" },
    { name: "Northern Arizona University", location: "Flagstaff, Arizona, USA", website: "https://www.nau.edu" },
    { name: "Northern Kentucky University", location: "Highland Heights, Kentucky, USA", website: "https://www.nku.edu" },
    { name: "New York Institute of Technology", location: "New York, New York, USA", website: "https://www.nyit.edu" },
    { name: "Northwest Missouri State University", location: "Maryville, Missouri, USA", website: "https://www.nwmissouri.edu" },
    { name: "University of North Dakota", location: "Grand Forks, North Dakota, USA", website: "https://www.und.edu" },
    { name: "University of North Alabama", location: "Florence, Alabama, USA", website: "https://www.una.edu" },
    { name: "University of New Haven", location: "West Haven, Connecticut, USA", website: "https://www.newhaven.edu" },
    { name: "Oklahoma City University", location: "Oklahoma City, Oklahoma, USA", website: "https://www.okcu.edu" },
    { name: "Pacific Lutheran University", location: "Tacoma, Washington, USA", website: "https://www.plu.edu" },
    { name: "New York University Tandon School of Engineering", location: "New York, New York, USA", website: "https://engineering.nyu.edu" },
    { name: "University of the Pacific", location: "Stockton, California, USA", website: "https://www.pacific.edu" },
    { name: "Rochester Institute of Technology", location: "Rochester, New York, USA", website: "https://www.rit.edu" },
    { name: "Rider University", location: "Lawrenceville, New Jersey, USA", website: "https://www.rider.edu" },
    { name: "Southern New Hampshire University", location: "Manchester, New Hampshire, USA", website: "https://www.snhu.edu" },
    { name: "Stevens Institute of Technology", location: "Hoboken, New Jersey, USA", website: "https://www.stevens.edu" },
    { name: "University of Southern Maine", location: "Portland, Maine, USA", website: "https://www.usm.maine.edu" },
    { name: "Texas Southern University", location: "Houston, Texas, USA", website: "https://www.tsu.edu" },
    { name: "University of Wisconsin-La Crosse", location: "La Crosse, Wisconsin, USA", website: "https://www.uwlax.edu" },
    { name: "Western Kentucky University", location: "Bowling Green, Kentucky, USA", website: "https://www.wku.edu" },
    { name: "Webster University", location: "St. Louis, Missouri, USA", website: "https://www.webster.edu" },
    { name: "Webber International University", location: "Babson Park, Florida, USA", website: "https://www.webber.edu" },
  ],
  Canada: [
    { name: "Algonquin College", location: "Ottawa, Ontario, Canada", website: "https://www.algonquincollege.com" },
    { name: "Brock University", location: "St. Catharines, Ontario, Canada", website: "https://brocku.ca" },
    { name: "Centennial College", location: "Toronto, Ontario, Canada", website: "https://www.centennialcollege.ca" },
    { name: "Dalhousie University", location: "Halifax, Nova Scotia, Canada", website: "https://www.dal.ca" },
    { name: "Fairleigh Dickinson University", location: "Vancouver, British Columbia, Canada", website: "https://www.fdu.edu" },
    { name: "George Brown College", location: "Toronto, Ontario, Canada", website: "https://www.georgebrown.ca" },
    { name: "Georgian College", location: "Barrie, Ontario, Canada", website: "https://www.georgiancollege.ca" },
    { name: "Humber College", location: "Toronto, Ontario, Canada", website: "https://humber.ca" },
    { name: "Mount Allison University", location: "Sackville, New Brunswick, Canada", website: "https://www.mta.ca" },
    { name: "Niagara College", location: "Welland, Ontario, Canada", website: "https://www.niagaracollege.ca" },
    { name: "Sheridan College", location: "Oakville, Ontario, Canada", website: "https://www.sheridancollege.ca" },
    { name: "Seneca College", location: "Toronto, Ontario, Canada", website: "https://www.senecacollege.ca" },
    { name: "Saskatchewan Polytechnic", location: "Saskatchewan, Canada", website: "https://saskpolytech.ca" },
    { name: "Okanagan College", location: "Kelowna, British Columbia, Canada", website: "https://www.okanagan.bc.ca" },
    { name: "Thompson Rivers University", location: "Kamloops, British Columbia, Canada", website: "https://www.tru.ca" },
    { name: "Laurentian University", location: "Sudbury, Ontario, Canada", website: "https://laurentian.ca" },
    { name: "University of Regina", location: "Regina, Saskatchewan, Canada", website: "https://www.uregina.ca" },
    { name: "Royal Roads University", location: "Victoria, British Columbia, Canada", website: "https://www.royalroads.ca" },
    { name: "Trent University", location: "Peterborough, Ontario, Canada", website: "https://www.trentu.ca" },
    { name: "University Canada West", location: "Vancouver, British Columbia, Canada", website: "https://www.ucanwest.ca" },
    { name: "University of Prince Edward Island", location: "Charlottetown, Prince Edward Island, Canada", website: "https://www.upei.ca" },
    { name: "University of the Fraser Valley", location: "Abbotsford, British Columbia, Canada", website: "https://www.ufv.ca" },
  ],

  Australia: [
    { name: "Australian National University", location: "Canberra, Australia", website: "https://www.anu.edu.au" },
    { name: "University of Adelaide", location: "Adelaide, Australia", website: "https://www.adelaide.edu.au" },
    { name: "Bond University", location: "Robina, Queensland, Australia", website: "https://bond.edu.au" },
    { name: "Federation University Australia", location: "Ballarat, Victoria, Australia", website: "https://federation.edu.au" },
    { name: "Box Hill Institute", location: "Box Hill, Victoria, Australia", website: "https://www.boxhill.edu.au" },
    { name: "CQUniversity", location: "Rockhampton, Queensland, Australia", website: "https://www.cqu.edu.au" },
    { name: "Charles Darwin University", location: "Darwin, Northern Territory, Australia", website: "https://www.cdu.edu.au" },
    { name: "Curtin University", location: "Perth, Western Australia, Australia", website: "https://www.curtin.edu.au" },
    { name: "Griffith University", location: "Queensland, Australia", website: "https://www.griffith.edu.au" },
    { name: "James Cook University", location: "Townsville, Queensland, Australia", website: "https://www.jcu.edu.au" },
    { name: "La Trobe University", location: "Melbourne, Victoria, Australia", website: "https://www.latrobe.edu.au" },
    { name: "Murdoch University", location: "Perth, Western Australia, Australia", website: "https://www.murdoch.edu.au" },
    { name: "Monash University", location: "Melbourne, Victoria, Australia", website: "https://www.monash.edu" },
    { name: "University of Melbourne", location: "Melbourne, Victoria, Australia", website: "https://www.unimelb.edu.au" },
    { name: "Queensland University of Technology", location: "Brisbane, Queensland, Australia", website: "https://www.qut.edu.au" },
    { name: "RMIT University", location: "Melbourne, Victoria, Australia", website: "https://www.rmit.edu.au" },
    { name: "Swinburne University of Technology", location: "Melbourne, Victoria, Australia", website: "https://www.swinburne.edu.au" },
    { name: "University of Southern Queensland", location: "Toowoomba, Queensland, Australia", website: "https://www.usq.edu.au" },
    { name: "University of Sydney", location: "Sydney, New South Wales, Australia", website: "https://www.sydney.edu.au" },
    { name: "University of Tasmania", location: "Hobart, Tasmania, Australia", website: "https://www.utas.edu.au" },
    { name: "University of Technology Sydney", location: "Sydney, New South Wales, Australia", website: "https://www.uts.edu.au" },
    { name: "Victoria University", location: "Melbourne, Victoria, Australia", website: "https://www.vu.edu.au" },
    { name: "University of Western Australia", location: "Perth, Western Australia, Australia", website: "https://www.uwa.edu.au" },
    { name: "University of Wollongong", location: "Wollongong, New South Wales, Australia", website: "https://www.uow.edu.au" },
    { name: "Western Sydney University", location: "Sydney, New South Wales, Australia", website: "https://www.westernsydney.edu.au" },
  ],

  NewZealand: [
    { name: "Auckland University of Technology", location: "Auckland, New Zealand", website: "https://www.aut.ac.nz" },
    { name: "University of Auckland", location: "Auckland, New Zealand", website: "https://www.auckland.ac.nz" },
    { name: "AIS St Helens", location: "Auckland, New Zealand", website: "https://www.ais.ac.nz" },
    { name: "University of Canterbury", location: "Christchurch, New Zealand", website: "https://www.canterbury.ac.nz" },
    { name: "Ara Institute of Canterbury", location: "Christchurch, New Zealand", website: "https://www.ara.ac.nz" },
    { name: "Eastern Institute of Technology", location: "Hawke's Bay, New Zealand", website: "https://www.eit.ac.nz" },
    { name: "Lincoln University", location: "Lincoln, New Zealand", website: "https://www.lincoln.ac.nz" },
    { name: "Lifeway College", location: "Snells Beach, New Zealand", website: "https://www.lifeway.ac.nz" },
    { name: "Manukau Institute of Technology", location: "Auckland, New Zealand", website: "https://www.manukau.ac.nz" },
    { name: "Massey University", location: "Palmerston North, New Zealand", website: "https://www.massey.ac.nz" },
    { name: "North Shore International Academy", location: "Auckland, New Zealand", website: "https://www.nsia.co.nz" },
    { name: "University of Otago", location: "Dunedin, New Zealand", website: "https://www.otago.ac.nz" },
    { name: "Unitec Institute of Technology", location: "Auckland, New Zealand", website: "https://www.unitec.ac.nz" },
    { name: "Victoria University of Wellington", location: "Wellington, New Zealand", website: "https://www.wgtn.ac.nz" },
    { name: "Toi Ohomai Institute of Technology", location: "Rotorua, New Zealand", website: "https://www.toiohomai.ac.nz" },
    { name: "Wellington Institute of Technology", location: "Wellington, New Zealand", website: "https://www.weltec.ac.nz" },
    { name: "University of Waikato", location: "Hamilton, New Zealand", website: "https://www.waikato.ac.nz" },
    { name: "Whitireia New Zealand", location: "Porirua, New Zealand", website: "https://www.whitireia.ac.nz" },
    { name: "Pacific International Hotel Management School", location: "New Plymouth, New Zealand", website: "https://www.pihms.ac.nz" },
  ],
  Ireland: [
    { name: "University College Dublin", location: "Dublin, Ireland", website: "https://www.ucd.ie" },
    { name: "Maynooth University", location: "Maynooth, Ireland", website: "https://www.maynoothuniversity.ie" },
    { name: "Dublin City University", location: "Dublin, Ireland", website: "https://www.dcu.ie" },
    { name: "University of Limerick", location: "Limerick, Ireland", website: "https://www.ul.ie" },
    { name: "National University of Ireland, Galway", location: "Galway, Ireland", website: "https://www.nuigalway.ie" },
    { name: "University College Cork", location: "Cork, Ireland", website: "https://www.ucc.ie" },
    { name: "Technological University Dublin", location: "Dublin, Ireland", website: "https://www.tudublin.ie" },
    { name: "Dundalk Institute of Technology", location: "Dundalk, Ireland", website: "https://www.dkit.ie" },
    { name: "Munster Technological University", location: "Cork, Ireland", website: "https://www.mtu.ie" },
    { name: "Waterford Institute of Technology", location: "Waterford, Ireland", website: "https://www.wit.ie" },
    { name: "National College of Ireland", location: "Dublin, Ireland", website: "https://www.ncirl.ie" },
    { name: "Dublin Business School", location: "Dublin, Ireland", website: "https://www.dbs.ie" },
  ],
  Germany: [
    { name: "Ludwig Maximilian University of Munich (LMU Munich)", location: "Munich, Germany", website: "https://www.lmu.de" },
    { name: "Technical University of Munich (TUM)", location: "Munich, Germany", website: "https://www.tum.de" },
    { name: "Heidelberg University", location: "Heidelberg, Germany", website: "https://www.uni-heidelberg.de" },
    { name: "Humboldt University of Berlin", location: "Berlin, Germany", website: "https://www.hu-berlin.de" },
    { name: "Free University of Berlin", location: "Berlin, Germany", website: "https://www.fu-berlin.de" },
    { name: "University of Göttingen", location: "Göttingen, Germany", website: "https://www.uni-goettingen.de" },
    { name: "RWTH Aachen University", location: "Aachen, Germany", website: "https://www.rwth-aachen.de" },
    { name: "University of Freiburg", location: "Freiburg, Germany", website: "https://www.uni-freiburg.de" },
    { name: "University of Stuttgart", location: "Stuttgart, Germany", website: "https://www.uni-stuttgart.de" },
    { name: "Karlsruhe Institute of Technology (KIT)", location: "Karlsruhe, Germany", website: "https://www.kit.edu" },
  ],
};
  